name: CustomActionMounikaWorkflow
on: 
  workflow_dispatch:

jobs:
  changeApproval:
    name: ServiceNow Change Approval
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow Change Approval
        uses: ServiceNow/servicenow-devops-change@dev
        id: create
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWD }}
          instance-url: ${{ secrets.SN_INSTANCE_NAME }}
          tool-id: ${{ secrets.SN_ORCH_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow Change Approval'
          change-request: '{
                      "setCloseCode": "true",
                      "attributes": {
                          "requested_by": {"user_name": "devops.system"},
                          "assignment_group": "a715cd759f2002002920bde8132e7018",
                          "priority": "2",
                          "comments": "This is a sample pipeline script to be added in your change step Test Mounika 2",
                          "work_notes": "Update this to work_note",
                          "start_date": "2023-09-07 11:59:59",
                          "end_date": "2023-09-09 11:59:59"
                      }
                  }'
          # change-request: '{
          #   "attributes": {
          #     "short_description": "Automated Software Deployment Mounika",
          #     "description": "Automated Software Deployment.",
          #     "assignment_group": "a715cd759f2002002920bde8132e7018",
          #     "implementation_plan": "Software update is tested and results can be found in Test Summaries Tab.",
          #     "backout_plan": "When software fails in production, the previous software release will be re-deployed.",
          #     "test_plan": "Testing if the software was successfully deployed",
          #     "chg_model": {"name": "normal"}
          #     }
          # }'
          # change-request: '{
          #   "attributes": {
          #     "requested_by": {
          #         "name": "test_user"
          #       },
          #       "assignment_group": {
          #         "name": "Change Approval Team"
          #       },
          #       "priority": "2",
          #       "comments": "This is a sample pipeline script to be added in your change step",
          #       "work_notes": "Update this to work_notes",
          #       "start_date": "2023-09-07 11:59:59",
          #       "end_date": "2023-09-09 11:59:59"
          #     }
          #   }'
          interval: '100'
          timeout: '3600'
